import AppProvider from "@/shared/providers/App.provider";
import "./globals.css";
import type { Metadata } from "next";
import NextTopLoader from 'nextjs-toploader';
import { ReactNode } from 'react';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html
            lang="en"
            className="w-full h-full antialiased"
        >
            <body className="w-full h-full flex flex-col">
                <NextTopLoader
                    color="#FF6B35"
                    height={2}
                    showSpinner={false}
                    speed={300}
                    crawlSpeed={100}
                />
                <AppProvider>
                    {children}
                </AppProvider>
            </body>
        </html>
    );
}
