version: '3.8'

services:
  # 1. DATABASE MONGO
  mongodb:
    image: mongo:7.0
    container_name: apc-mongodb-container
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    ports:
      - "9265:9265"
    volumes:
      - custom_data:/data/db

  # 2. TỰ ĐỘNG CHẠY SEED DATA (Sử dụng script shell có sẵn trong project)
  mongodb-seed:
    image: mongo:7.0
    container_name: apc-mongodb-seed-container
    volumes:
      - ./data:/data
    # Đợi mongo khởi động xong -> dùng mongosh chạy các file schema .js tuần tự
    entrypoint: >
      bash -c "
        echo 'Waiting for mongodb...'
        until mongosh --host mongodb-standard:9265 -u root -p rootpw --eval 'db.runCommand({ping:1})' &>/dev/null; do
          sleep 2
        done
        echo 'MongoDB is up! Starting seed...'
        for file in $(ls /data/schemas/*.js | sort); do
          echo 'Running script: ' $$file
          mongosh mongodb://root:rootpw@mongodb:9265/affiliate-product-catalog?authSource=admin --file $$file --quiet
        done
        echo 'Finish seed data!'
      "
    depends_on:
      - mongodb-standard

  # 3. BACKEND (NESTJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apc-backend-container
    ports:
      - "9270:9270"
    environment:
      # LƯU Ý: Trong môi trường Docker, thay 'localhost' bằng tên service 'mongodb-standard'
      MONGO_URI: mongodb://root:rootpw@mongodb-standard:9265/affiliate-product-catalog?authSource=admin
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb-standard
    restart: unless-stopped
  frontend-dev: # Môi trường Dev cho Frontend
    container_name: apc-frontend-dev-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development # Chỉ định dừng lại ở tầng development trong Dockerfile
    ports:
      - "9260:9260"
    env_file: # Tự động nạp toàn bộ biến từ file .env.development vào hệ thống
      - ./frontend/.env.development
    volumes:
      - ./frontend:/app # Đồng bộ code để hot-reload
      - /app/node_modules # Giữ node_modules độc lập trong container, tránh xung đột cấu hình máy thật
      - /app/.next # Giữ cache Next.js độc lập để tăng tốc độ tải trang lúc dev
    restart: unless-stopped

  # Lệnh chạy: docker compose up frontend-prod --build -d
  frontend-prod: # Môi trường Product cho Frontend
    container_name: apc-frontend-prod-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production # Bỏ qua stage 2, chạy các stage còn lại
    ports:
      - "9260:9260"
    env_file:
      - ./frontend/.env.production # Tự động nạp toàn bộ biến từ file .env.production vào hệ thống
    restart: unless-stopped

  # 5. ADMIN (REACT + VITE)
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: apc-admin-container
    ports:
      - "9261:9261"
    environment:
      VITE_API_URL: http://localhost:9261
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  custom_data: