services:
  mongodb:
    image: mongo:7.0
    container_name: apc-mongodb-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      # Bảo mật: Chỉ cho phép nội bộ server kết nối, chặn port công cộng
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - apc_data:/data/db

  backend:
    container_name: apc-backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env.production
    environment:
      - PORT=${BACKEND_PORT}
      - DISK_PATH=/app/disk
      - MONGODB_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}/affiliate-product-catalog?authSource=admin
    volumes:
      - ${DISK_PATH}:/app/disk
    restart: always
    depends_on:
      - mongodb

  frontend:
    container_name: apc-frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - NEXT_PUBLIC_SOCKET_PATH=${NEXT_PUBLIC_SOCKET_PATH}
        - NODE_ENV=production
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env.production
    environment:
      - PORT=${FRONTEND_PORT}
    restart: always
    depends_on:
      - backend

  admin:
    container_name: apc-admin-container
    build:
      context: ./admin
      dockerfile: Dockerfile
      target: production 
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_SOCKET_PATH=${VITE_SOCKET_PATH}
        - NODE_ENV=production
    ports:
      - "${ADMIN_PORT}:80"
    env_file:
      - .env.production
    restart: always
    depends_on:
      - backend

volumes:
  apc_data: